export default {
  'Africa/Abidjan': 'Africa/Abidjan',
  'Africa/Accra': 'Africa/Accra',
  'Africa/Addis_Ababa': 'Africa/Addis Ababa',
  'Africa/Algiers': 'Africa/Algiers',
  'Africa/Asmara': 'Africa/Asmara',
  'Africa/Asmera': 'Africa/Asmera',
  'Africa/Bamako': 'Africa/Bamako',
  'Africa/Bangui': 'Africa/Bangui',
  'Africa/Banjul': 'Africa/Banjul',
  'Africa/Bissau': 'Africa/Bissau',
  'Africa/Blantyre': 'Africa/Blantyre',
  'Africa/Brazzaville': 'Africa/Brazzaville',
  'Africa/Bujumbura': 'Africa/Bujumbura',
  'Africa/Cairo': 'Africa/Cairo',
  'Africa/Casablanca': 'Africa/Casablanca',
  'Africa/Ceuta': 'Africa/Ceuta',
  'Africa/Conakry': 'Africa/Conakry',
  'Africa/Dakar': 'Africa/Dakar',
  'Africa/Dar_es_Salaam': 'Africa/Dar es Salaam',
};
